AWSTemplateFormatVersion: 2010-09-09
Description: ---

Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    DeletionPolicy: Retain
    Properties:
      ImageId: ami-0a24ce26f4e187f9a #Region: us-east-1
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: test-import-terraform
Outputs:
  InstanceID:
    Description: Instance ID
    Value: !Ref myEC2Instance